version: "3.9"

services:
  bdd:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env


volumes:
  postgres_data:
      